[project]
name = "ami-client-delivery"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.13.*"
dependencies = [
    "ayon-python-api>=1.2.22",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "pydantic>=2.13.4",
    "python-multipart>=0.0.32",
    "rvx-beryl>=0.5.1",
    "shotgun-api3>=3.10.3",
    "uvicorn>=0.52.1",
]

[[tool.uv.index]]
name = "rvx-internal"
url = "https://nexus.eu.rvx.is/repository/rvx-internal/simple"
