[tool.poetry]
name = "shotgrid-whiteboard"
version = "0.6.10+rvx.16"
description = "Whiteboard webpage"
authors = ["Oscar Domingo <oscar.domingo@ynput.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
uvicorn = "*"
shotgun-api3 = "*"
fastapi = "*"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
