[project]
name = "shotgrid-ami"
version = "0.6.14+rvx.16"
description = "Service that handles the shotgun action menu items"
requires-python = "==3.10.*"
dependencies = [
    "arrow",
    "ayon-python-api==1.2.6",
    "shotgun-api3==3.8.5",
    "fastapi>=0.119.1",
    "uvicorn>=0.38.0",
    "jinja2>=3.1.6",
    "python-multipart>=0.0.20",
    "corder",
    "openpyxl",
    "pydantic==1.10.18",
    "rvx-beryl",
    "rvx_log",
]

[project.optional-dependencies]
dev = [
    "pytest>=5.2,<6.0",
]

[[tool.uv.index]]
name = "rvx-group"
url = "https://nexus.eu.rvx.is/repository/rvx-group/simple"
default = true
